[/Script/EngineSettings.GameMapsSettings]
; Mapa template do engine (chão + luz) para jogar sem criar nada no editor.
; Quando criar o mapa real, troque para /Game/Maps/L_Cerrado.L_Cerrado
GameDefaultMap=/Engine/Maps/Templates/Template_Default.Template_Default
EditorStartupMap=/Engine/Maps/Templates/Template_Default.Template_Default
GlobalDefaultGameMode=/Script/TerraForge.TerraForgeGameMode

[/Script/Engine.RendererSettings]
r.DynamicGlobalIlluminationMethod=1
r.ReflectionMethod=1
r.Lumen.HardwareRayTracing=0
r.Nanite=1
r.DefaultFeature.AutoExposure.ExtendDefaultLuminanceRange=True

[/Script/Engine.Engine]
+ActiveGameNameRedirects=(OldGameName="TP_Blank",NewGameName="/Script/TerraForge")

[/Script/HardwareTargeting.HardwareTargetingSettings]
TargetedHardwareClass=Desktop
AppliedTargetedHardwareClass=Desktop
DefaultGraphicsPerformance=Maximum
AppliedDefaultGraphicsPerformance=Maximum

[/Script/WorldPartitionEditor.WorldPartitionEditorSettings]
CommandletClass=Class'/Script/UnrealEd.WorldPartitionConvertCommandlet'
